In [6]:
import pandas as pd
from scipy import stats
url = "https://raw.githubusercontent.com/nkmwicz/data-for-students/refs/heads/main/soccer-players.csv"

df = pd.read_csv(url)
df.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0

In [7]:
df.shape

(32403, 23)

In [10]:
df.describe()

,player_id,last_season,current_club_id,height_in_cm,market_value_in_eur,highest_market_value_in_eur
count,3.240300e+04,32403.000000,32403.000000,30059.000000,3.086900e+04,3.086900e+04
mean,3.445789e+05,2019.337777,4809.252045,182.291161,1.611350e+06,3.675045e+06
std,2.806831e+05,3.965914,11601.982978,6.971224,6.362017e+06,9.653897e+06
min,1.000000e+01,2012.000000,3.000000,17.000000,1.000000e+04,1.000000e+04
25%,1.066980e+05,2016.000000,403.000000,178.000000,1.000000e+05,2.750000e+05
50%,2.824210e+05,2020.000000,1071.000000,183.000000,2.500000e+05,8.000000e+05
75%,5.242085e+05,2023.000000,3060.000000,187.000000,7.000000e+05,2.800000e+06
max,1.309800e+06,2024.000000,110302.000000,207.000000,2.000000e+08,2.000000e+08

In [11]:
df ['height_in_cm'].skew()

np.float64(-1.7751475048518246)

In [12]:
df['height_in_cm'].min()

np.float64(17.0)

In [23]:
inch_ratio = 0.39

df['height_in_ft'] = (df['height_in_cm'] * inch_ratio) / 12
df['height_in_ft'].mean()

np.float64(5.924462723310822)

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32403 entries, 0 to 32402
Data columns (total 25 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   player_id                             32403 non-null  int64
 1   first_name                            30345 non-null  str
 2   last_name                             32403 non-null  str
 3   name                                  32403 non-null  str
 4   last_season                           32403 non-null  int64
 5   current_club_id                       32403 non-null  int64
 6   player_code                           32403 non-null  str
 7   country_of_birth                      29600 non-null  str
 8   city_of_birth                         29942 non-null  str
 9   country_of_citizenship                32023 non-null  str
 10  date_of_birth                         32356 non-null  str
 11  sub_position                          32218 non-null  str
 12  position                              32403 non-null  str
 13  foot                                  29810 non-null  str
 14  height_in_cm                          30059 non-null  float64
 15  contract_expiration_date              20272 non-null  str
 16  agent_name                            16388 non-null  str
 17  image_url                             32403 non-null  str
 18  url                                   32403 non-null  str
 19  current_club_domestic_competition_id  32403 non-null  str
 20  current_club_name                     32403 non-null  str
 21  market_value_in_eur                   30869 non-null  float64
 22  highest_market_value_in_eur           30869 non-null  float64
 23  height_in_inch                        30059 non-null  float64
 24  height_in_ft                          30059 non-null  float64
dtypes: float64(5), int64(3), str(17)
memory usage: 6.2 MB

In [25]:
for col in df.columns:
    print(col)

player_id
first_name
last_name
name
last_season
current_club_id
player_code
country_of_birth
city_of_birth
country_of_citizenship
date_of_birth
sub_position
position
foot
height_in_cm
contract_expiration_date
agent_name
image_url
url
current_club_domestic_competition_id
current_club_name
market_value_in_eur
highest_market_value_in_eur
height_in_inch
height_in_ft

In [28]:
skew = stats.skew(df['height_in_cm'], nan_policy='omit')
kurt = stats.kurtosis(df['height_in_cm'], nan_policy='omit')
print (f"skew: {skew}")
print(f"kurtosis: {kurt}")

skew: -1.7750589204621978
kurtosis: 40.36548066183286

In [30]:
df['date_of_birth'] = pd.to_datetime(df['date_of_birth'])

In [33]:
df['date_mth'] = df['date_of_birth'].dt.month
df['date_mth'].skew()

np.float64(0.2620706716108742)

In [38]:
for x in range(1, 13):
    x = float(x)
    perc = df ['birth_mth'].value_counts().loc[x] / df['birth_mth'].count()
    print(x, perc)

KeyError: 'birth_mth'